spring:
  datasource:
    url: jdbc:mysql://121.40.24.241:3306/E?useUnicode=yes&characterEncoding=utf8
    username: root
    password: zhangyu
    driver-class-name: com.mysql.jdbc.Driver
    
server: 
  port: 9527